name: Mobile

on:
  push:
    branches: [ dev, production, main ]
  pull_request:
    branches: [ dev, production, main ]
 
jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Build and Test
      working-directory: ./mobile
      run: |
        xcodebuild test \
          -scheme HelloWorld \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -enableCodeCoverage YES \
          | xcpretty